/usr/bin/ld: cluster.o: in function `cluster':
/home/users/acsilveira/rodinia/openmp/kmeans/kmeans_openmp/cluster.c:94: undefined reference to `kmeans_clustering'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:6: kmeans] Error 1
make: *** [Makefile:4: OPENMP/kmeans] Error 2
/var/spool/slurmd/job702363/slurm_script: line 55: cd: openmp/leukocyte: No such file or directory
make: *** No rule to make target 'clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
python3: can't open file '/home/users/acsilveira/rodinia/openmp/carbon.py': [Errno 2] No such file or directory
make: nvcc: No such file or directory
make: *** [Makefile:4: backprop] Error 127
sh: 1: ./backprop: not found
sh: 1: ./backprop: not found
sh: 1: ./backprop: not found
sh: 1: ./backprop: not found
sh: 1: ./backprop: not found
sh: 1: ./backprop: not found
sh: 1: ./backprop: not found
sh: 1: ./backprop: not found
sh: 1: ./backprop: not found
sh: 1: ./backprop: not found
sh: 1: ./backprop: not found
sh: 1: ./backprop: not found
sh: 1: ./backprop: not found
sh: 1: ./backprop: not found
sh: 1: ./backprop: not found
sh: 1: ./backprop: not found
sh: 1: ./backprop: not found
sh: 1: ./backprop: not found
sh: 1: ./backprop: not found
sh: 1: ./backprop: not found
